[package]
name = "moc-parser"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
itertools = "0.14.0"
log = "0.4.28"
moc-common = {path = "../moc-common"}
