[package]
name = "moc-common"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
